let data=[
    {
        id:0,
        title: "Narcos",
        movieHall:"INOX",
        Genre: "Crime",
        Language: "Tamil",
        date: "8th Oct. 2014",
        city: "Ahmedabad",
        format:"4DX",
        time: "14:00",
        tickets: ['A1'],
        amount: 420,
        img:"http://ia.media-imdb.com/images/M/MV5BMTU0ODQ4NDg2OF5BMl5BanBnXkFtZTgwNzczNTE4OTE@._V1_SX300.jpg"
    },
    {
        id:1,
        title: "Breaking Bad",
        movieHall:"Cinepolis",
        Genre: "Drama",
        Language: "English",
        date: "8th Oct. 2014",
        city: "NCR",
        format:"4DX",
        time: "14:00",
        tickets: ['A1'],
        amount: 150,
        img:"http://ia.media-imdb.com/images/M/MV5BMTQ0ODYzODc0OV5BMl5BanBnXkFtZTgwMDk3OTcyMDE@._V1_SX300.jpg"
    },
    {
        id:2,
        title: "Assassin's Creed",
        movieHall:"Cinepolis",
        Genre: "Action",
        Language: "English",
        date: "8th Oct. 2014",
        city: "Chennai",
        format:"4DX",
        time: "14:00",
        tickets: ['A1'],
        amount: 120,
        img:"http://ia.media-imdb.com/images/M/MV5BMTU2MTQwMjU1OF5BMl5BanBnXkFtZTgwMDA5NjU5ODE@._V1_SX300.jpg"
    },
    {
        id:3,
        title: "Luke Cage",
        movieHall:"INOX",
        Genre: "Action",
        Language: "English",
        date: "8th Oct. 2014",
        city: "Banglore",
        format:"3D",
        time: "14:00",
        tickets: ['A1'],
        amount: 120,
        img:"http://ia.media-imdb.com/images/M/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_SX300.jpg"
    },
    {
        id:4,
        title: "Power",
        movieHall:"INOX",
        Genre: "Drama",
        Language: "Tamil",
        date: "8th Oct. 2014",
        city: "Mumbai",
        format:"MX4D",
        time: "14:00",
        tickets: ['A1'],
        amount: 120,
        img:"http://ia.media-imdb.com/images/M/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_SX300.jpg"
    },
    {
        id:5,
        title: "Gotham",
        movieHall:"INOX",
        Genre: "Drama",
        Language: "English",
        date: "8th Oct. 2014",
        city: "Mumbai",
        format:"2D",
        time: "14:00",
        tickets: ['A1'],
        amount: 120,
        img:"http://ia.media-imdb.com/images/M/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_SX300.jpg"
    },
    {
        id:6,
        title: "Vikings",
        movieHall:"INOX",
        Genre: "Action",
        Language: "English",
        date: "8th Oct. 2014",
        city: "Chennai",
        format:"4DX",
        time: "14:00",
        tickets: ['A1'],
        amount: 120,
        img:"http://ia.media-imdb.com/images/M/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_SX300.jpg"
    },
    {
        id:7,
        title: "Game of Thrones",
        movieHall:"INOX",
        Genre: "Action",
        Language: "Malyalam",
        date: "8th Oct. 2014",
        city: "Hyderabad",
        format:"4DX",
        time: "14:00",
        tickets: ['A1'],
        amount: 120,
        img:"http://ia.media-imdb.com/images/M/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_SX300.jpg"
    },
    {
        id:8,
        title: "Interstellar",
        movieHall:"INOX",
        Genre: "Drama",
        Language: "English",
        date: "8th Oct. 2014",
        city: "Hyderabad",
        format:"4DX",
        time: "14:00",
        tickets: ['A1'],
        amount: 120,
        img:"http://ia.media-imdb.com/images/M/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_SX300.jpg"
    },
    {
        id:9,
        title: "The Wolf of Wall Street",
        movieHall:"INOX",
        Genre: "Comedy",
        Language: "English",
        date: "8th Oct. 2014",
        city: "NCR",
        format:"MX4D",
        time: "14:00",
        tickets: ['A1'],
        amount: 120,
        img:"http://ia.media-imdb.com/images/M/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_SX300.jpg"
    },
    {
        id:10,
        title: "The Avengers",
        movieHall:"INOX",
        Genre: "Action",
        Language: "English",
        date: "8th Oct. 2014",
        city: "NCR",
        format:"MX4D",
        time: "14:00",
        tickets: ['A1'],
        amount: 120,
        img:"http://ia.media-imdb.com/images/M/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_SX300.jpg"
    },
    {
        id:11,
        title: "I Am Legend",
        movieHall:"INOX",
        Genre: "Drama",
        Language: "English",
        date: "8th Oct. 2014",
        city: "Ahmedabad",
        format:"MX4D",
        time: "14:00",
        tickets: ['A1'],
        amount: 120,
        img:"http://ia.media-imdb.com/images/M/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_SX300.jpg"
    },
    {
        id:12,
        title: "Avatar",
        movieHall:"INOX",
        Genre: "Action",
        Language: "English",
        date: "8th Oct. 2014",
        city: "Banglore",
        format:"MX4D",
        time: "14:00",
        tickets: ['A1'],
        amount: 120,
        img:"http://ia.media-imdb.com/images/M/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_SX300.jpg"
    },
    {
        id:13,
        title: "300",
        movieHall:"INOX",
        Genre: "Drama",
        Language: "English",
        date: "8th Oct. 2014",
        city: "Banglore",
        format:"MX4D",
        time: "14:00",
        tickets: ['A1'],
        amount: 120,
        img:"http://ia.media-imdb.com/images/M/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_SX300.jpg"
    },
]
let movieHall=[
    {id:1,name:"CinePolis:DLF Place, Saket",show:'Morning',time:['9:00AM','6:00AM','11:15AM']},
    {id:2,name:"CinePolis:DLF Place, Saket",show:'Afternoon',time:['2:00PM','3:00PM','1:15PM']},
    {id:3,name:"CinePolis:DLF Place, Saket",show:'Evening',time:['4:00PM','5:00PM','6:15PM']},
    {id:4,name:"CinePolis:DLF Place, Saket",show:'Night',time:['7:00PM','9:00PM','11:15PM']},
    {id:5,name:"CinePolis:Cross river mall, Shahdara",show:'Morning',time:['9:00AM','6:00AM','11:15AM']},
    {id:6,name:"CinePolis:Cross river mall, Shahdara",show:'Afternoon',time:['2:00PM','3:00PM','1:15PM']},
    {id:7,name:"CinePolis:Cross river mall, Shahdara",show:'Evening',time:['4:00PM','5:00PM','6:15PM']},
    {id:8,name:"CinePolis:Cross river mall, Shahdara",show:'Night',time:['7:00PM','9:00PM','11:15PM']},
    {id:9,name:"Carnival:TGIP",show:'Morning',time:['9:00AM','6:00AM','11:15AM']},
    {id:10,name:"Carnival:TGIP",show:'Afternoon',time:['2:00PM','3:00PM','1:15PM']},
    {id:11,name:"Carnival:TGIP",show:'Evening',time:['4:00PM','5:00PM','6:15PM']},
    {id:12,name:"Carnival:TGIP",show:'Night',time:['7:00PM','9:00PM','11:15PM']},
]

module.exports.data=data;
module.exports.movieHall=movieHall;